[project]
name = "chat-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.136.1",
    "uvicorn[standard]==0.46.0",
    "pydantic==2.13.4",
    "pydantic-settings==2.14.1",
    "pytest==8.2.0",
    "pytest-asyncio==0.23.6",
    "passlib[argon2]==1.7.4",
    "tortoise-orm[asyncpg]>=0.31.0",
    "tortoise-cli>=0.2.0",
    "python-multipart>=0.0.28",
    "python-jose>=3.5.0",
]
[tool.tortoise]
config = "app.infrastructure.database.TORTOISE_ORM"
